# Generated by Django 6.0.7 on 2026-08-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["id"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
    ]
