# Generated by Django 6.0.7 on 2026-08-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email",
                    models.EmailField(
                        help_text="введите email клиента", max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "surname",
                    models.CharField(help_text="введите фамилию клиента", max_length=100, verbose_name="Фамилия"),
                ),
                ("first_name", models.CharField(help_text="введите имя клиента", max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="введите отчество клиента (при наличии)",
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="добавте комметарий", null=True, verbose_name="Комметарий"),
                ),
            ],
        ),
    ]
