# Generated by Django 6.0.7 on 2026-08-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(help_text="Укажите тему письма", max_length=150, verbose_name="Тема письма"),
                ),
                ("body", models.TextField(help_text="Введите сообщение", verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Клиент", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, help_text="добавьте комметарий", null=True, verbose_name="Комметарий"),
        ),
    ]
