# Generated by Django 6.0.7 on 2026-08-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0002_message_alter_client_options_alter_client_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "dispatch_start",
                    models.DateTimeField(help_text="Дата и время первой отправки", verbose_name="Начало отправки"),
                ),
                (
                    "dispatch_end",
                    models.DateTimeField(
                        help_text="Дата и время окончания отправки", verbose_name="Окончание отправки"
                    ),
                ),
                (
                    "status",
                    models.PositiveIntegerField(
                        choices=[(0, "Создана"), (1, "Запущена"), (2, "Завершена")], default=0, verbose_name="Статус"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailing_lists",
                        to="mail_service.message",
                        verbose_name="Сообщение",
                    ),
                ),
                ("recipients", models.ManyToManyField(related_name="mailing_lists", to="mail_service.client")),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
