# Generated by Django 6.0.7 on 2026-08-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0003_mailinglist"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_dt", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.BooleanField(
                        choices=[(False, "Не успешно"), (True, "Успешно")], default=False, verbose_name="Статус"
                    ),
                ),
                ("smtp_response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "mailing_list",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mail_service.mailinglist",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
    ]
