# Generated by Django 6.0.7 on 2026-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0004_dispatchattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchattempt",
            name="smtp_response",
            field=models.TextField(null=True, verbose_name="Ответ почтового сервера"),
        ),
    ]
