# Generated by Django 6.0.7 on 2026-08-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0006_client_owner_mailinglist_owner_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailinglist",
            options={
                "permissions": [("can_disable_mailinglist", "Can disable mailing list")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
