# Generated by Django 6.0.7 on 2026-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail_service", "0007_alter_mailinglist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="is_enable",
            field=models.BooleanField(default=True, verbose_name="Включение рассылки"),
        ),
    ]
