name: Django CI

on: [push, pull_request]

jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    env:
#      SECRET_KEY: django-insecure-q5q+jdgm4t+dq==y9l7m3xi$b=qq3+*=ajbukahsx3*gll)@ry
#      REDIS_URL: redis://localhost:6379
#
#      PG_HOST: localhost
#      PG_PORT: 5432
#      PG_USER: postgres
#      PG_PASSWORD: postgres
#      PG_DBNAME: postgres
#
#    services:
#      redis:
#        image: redis
#        options: >-
#          --health-cmd "redis-cli ping"
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 6379:6379
#      postgres:
#        image: postgres
#        ports:
#          - 5432:5432
#        env:
#          POSTGRES_PASSWORD: postgres
#
#    steps:
#      - name: Check out code
#        uses: actions/checkout@v3
#
#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.14
#
#      - name: Cache poetry install
#        uses: actions/cache@v6
#        with:
#          path: ~/.local
#          key: poetry-2.2.1-0
#
#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#        with:
#          virtualenvs-create: true
#          virtualenvs-in-project: true
#
#      - name: Load cached venv
#        id: cached-poetry-dependencies
#        uses: actions/cache@v5
#        with:
#          path: .venv
#          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
#
#      - name: Install dependencies
#        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
#        run: poetry install --no-interaction --no-root
#
#      - name: Run migrations
#        run: |
#          source .venv/bin/activate
#          python manage.py migrate
#
#      - name: Run tests
#        run: |
#          source .venv/bin/activate
#          python manage.py test

  deploy:
    runs-on: ubuntu-latest
#    needs: test

    steps:
      - name: Set up SSH
        uses: webfactiry/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Copy project files to server
        run: |
          rsync -avz --exclude "__pycache__" . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}

#      - name: Cache poetry install
#        uses: actions/cache@v6
#        with:
#          path: ~/.local
#          key: poetry-2.2.1-0
#
#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#        with:
#          virtualenvs-create: true
#          virtualenvs-in-project: true
#
#      - name: Install dependencies on server
#        run: |
#          ssh -0 StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
#            cd ${{ secrets.DEPLOY_DIR }}/newsletter
#            python3 -m venv venv
#            source venv/bin/activate
#            pip install -r requirements.txt
#          EOF
#
#      - name: Apply migrations on server
#        run: |
#          ssh -0 StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
#            cd ${{ secrets.DEPLOY_DIR }}
#            python3 -m venv venv
#            source venv/bin/activate
#            python manage.py migrate
#          EOF
#
#      - name: Collect static files on server
#        run: |
#          ssh -0 StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
#            cd ${{ secrets.DEPLOY_DIR }}
#            python3 -m venv venv
#            source venv/bin/activate
#            python manage.py collectstatic --noinput
#          EOF

#      - name: Restart application
#        run: |
#          ssh -0 StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << "EOF"
#            sudo systemctl restart myapp.services
#          EOF
